<a href="https://colab.research.google.com/github/shanami/DSCI-261-eng/blob/main/missing_data_overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd

uploaded = files.upload()  # now select file button

# Read the uploaded file
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
df.head()

Saving world_development_indicators.csv to world_development_indicators (1).csv

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,Country Name,Country Code,country_category,is_region,planet
0,Afghanistan,97.700000,1.213235,9.0,11.777236,519.884773,2058.383832,65.656000,62.70100,64.130000,55.595993,36296400.0,NaN,14.090000,10.416000,11.184000,2017,Afghanistan,AFG,DEVELOPING,0,Earth
1,Albania,100.000000,31.714076,9.0,5.010597,4531.020806,13037.010016,80.148000,76.60100,78.333000,104.870693,2873457.0,NaN,12.563000,14.590000,13.750000,2017,Albania,ALB,DEVELOPING,0,Earth
2,Algeria,100.000000,9.130677,10.0,6.380329,4111.294110,11737.409353,77.735000,75.30700,76.499000,17.377715,41389198.0,NaN,21.114000,10.021000,11.996000,2017,Algeria,DZA,DEVELOPING,0,Earth
3,Angola,41.962894,19.079250,6.0,2.791503,4095.812942,7310.901738,63.252000,57.67700,60.379000,23.916538,29816748.0,NaN,7.467000,6.769000,7.119000,2017,Angola,AGO,DEVELOPING,0,Earth
4,Arab World,90.283638,27.360620,9.0,5.561266,6108.588220,14562.367966,73.493366,69.92125,71.622526,36.669804,411898967.0,NaN,20.361396,8.097088,10.641313,2017,Arab World,ARB,NaN,1,Earth

In [ ]:
import pandas as pd

# Show all rows and all columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

df = pd.read_csv('world_development_indicators (1).csv')
df  # displays the entire dataframe

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,Country Name,Country Code,country_category,is_region,planet
0,Afghanistan,97.700000,1.213235,9.0,11.777236,519.884773,2058.383832,65.656000,62.701000,64.130000,55.595993,3.629640e+07,NaN,14.090000,10.416000,11.184000,2017,Afghanistan,AFG,DEVELOPING,0,Earth
1,Albania,100.000000,31.714076,9.0,5.010597,4531.020806,13037.010016,80.148000,76.601000,78.333000,104.870693,2.873457e+06,NaN,12.563000,14.590000,13.750000,2017,Albania,ALB,DEVELOPING,0,Earth
2,Algeria,100.000000,9.130677,10.0,6.380329,4111.294110,11737.409353,77.735000,75.307000,76.499000,17.377715,4.138920e+07,NaN,21.114000,10.021000,11.996000,2017,Algeria,DZA,DEVELOPING,0,Earth
3,Angola,41.962894,19.079250,6.0,2.791503,4095.812942,7310.901738,63.252000,57.677000,60.379000,23.916538,2.981675e+07,NaN,7.467000,6.769000,7.119000,2017,Angola,AGO,DEVELOPING,0,Earth
4,Arab World,90.283638,27.360620,9.0,5.561266,6108.588220,14562.367966,73.493366,69.921250,71.622526,36.669804,4.118990e+08,NaN,20.361396,8.097088,10.641313,2017,Arab World,ARB,NaN,1,Earth
5,Argentina,100.000000,53.115204,14.0,10.457044,14613.041825,23597.117753,79.726000,72.924000,76.372000,16.094191,4.404481e+07,NaN,9.464000,7.527000,8.347000,2017,Argentina,ARG,NaN,0,Earth
6,Armenia,100.000000,63.736251,12.0,10.362705,3914.501268,12115.057009,78.165000,71.115000,74.797000,103.435511,2.944809e+06,NaN,17.471001,17.906000,17.705000,2017,Armenia,ARM,DEVELOPING,0,Earth
7,Australia,100.000000,160.324387,10.0,9.205448,54027.966818,48870.588287,84.600000,80.500000,82.500000,3.198361,2.460186e+07,NaN,5.668000,5.525000,5.591000,2017,Australia,AUS,DEVELOPED,0,Earth
8,Austria,100.000000,165.036774,13.0,10.382624,47426.511960,54496.163694,84.000000,79.400000,81.643902,106.607445,8.797566e+06,NaN,5.031000,5.908000,5.499000,2017,Austria,AUT,DEVELOPED,0,Earth
9,Azerbaijan,100.000000,32.159237,10.0,3.736515,4147.089716,14121.406936,75.215000,70.128000,72.693000,119.197206,9.854033e+06,NaN,5.927000,4.119000,5.000000,2017,Azerbaijan,AZE,DEVELOPING,0,Earth
10,"Bahamas, The",100.000000,122.946505,12.0,6.831299,32718.638101,36297.307023,75.718000,71.300000,73.554000,38.137962,3.817610e+05,NaN,11.391000,8.360000,9.800000,2017,"Bahamas, The",BHS,DEVELOPING,0,Earth
11,Bahrain,100.000000,NaN,9.0,4.748131,23742.985017,47709.873814,78.143000,76.188000,77.032000,1920.403524,1.494074e+06,NaN,2.792000,0.148000,0.701000,2017,Bahrain,BHR,NaN,0,Earth
12,Bangladesh,88.000000,8.360076,5.0,2.275222,1563.913699,4161.089713,73.978000,70.409000,72.052000,1226.631274,1.596706e+08,NaN,6.745000,3.347000,4.372000,2017,Bangladesh,BGD,DEVELOPING,0,Earth
13,Barbados,100.000000,26.300050,11.0,6.622170,17391.425866,15788.820516,80.307000,77.562000,78.981000,665.658140,2.862330e+05,NaN,10.042000,9.487000,9.761000,2017,Barbados,BRB,NaN,0,Earth
14,Belarus,100.000000,55.667175,9.0,5.759748,5761.747120,18280.198919,79.200000,69.300000,74.129268,46.792242,9.498264e+06,NaN,4.039000,7.228000,5.650000,2017,Belarus,BLR,NaN,0,Earth
15,Belgium,100.000000,85.639518,12.0,10.406083,44192.623027,50615.365831,83.900000,79.200000,81.492683,375.665720,1.137516e+07,NaN,7.054000,7.114000,7.086000,2017,Belgium,BEL,DEVELOPED,0,Earth
16,Belize,98.251152,38.514422,8.0,5.701254,4887.577208,7108.866700,77.453000,71.533000,74.365000,16.473871,3.757690e+05,NaN,9.801000,4.589000,6.595000,2017,Belize,BLZ,DEVELOPING,0,Earth
17,Benin,34.500000,4.885356,6.0,2.644484,1136.592847,3044.513887,62.687000,59.633000,61.174000,99.106101,1.117520e+07,NaN,2.664000,2.261000,2.459000,2017,Benin,BEN,DEVELOPING,0,Earth
18,Bhutan,97.700000,39.448449,NaN,3.244916,3286.574703,11142.399948,71.444000,70.822000,71.129000,19.546141,7.455680e+05,NaN,3.158000,1.803000,2.358000,2017,Bhutan,BTN,DEVELOPING,0,Earth
19,Bolivia,91.800000,39.656907,14.0,6.490195,3351.124044,8423.696806,73.878000,68.173000,70.945000,10.332183,1.119285e+07,NaN,4.071000,3.369000,3.670000,2017,Bolivia,BOL,DEVELOPING,0,Earth
20,Bosnia and Herzegovina,100.000000,53.893254,9.0,8.931590,5394.591220,13788.482064,79.581000,74.622000,77.128000,65.459512,3.351527e+06,NaN,23.099001,18.839001,20.527000,2017,Bosnia and Herzegovina,BIH,DEVELOPING,0,Earth
21,Botswana,62.602352,35.415198,NaN,6.134568,7893.232534,17253.280629,71.559000,65.790000,68.812000,3.890967,2.205128e+06,NaN,20.649000,14.510000,17.504999,2017,Botswana,BWA,DEVELOPING,0,Earth
22,Brazil,100.000000,107.871669,14.0,9.469337,9925.386238,14519.849130,79.156000,71.804000,75.456000,24.866038,2.078338e+08,NaN,14.718000,11.370000,12.822000,2017,Brazil,BRA,DEVELOPING,0,Earth
23,Brunei Darussalam,100.000000,69.594351,9.0,2.270364,28572.146778,60995.681114,76.819000,74.454000,75.585000,80.545161,4.244730e+05,NaN,9.985000,8.819000,9.316000,2017,Brunei Darussalam,BRN,NaN,0,Earth
24,Bulgaria,100.000000,94.667108,11.0,7.453268,8334.081728,21370.782659,78.400000,71.400000,74.814634,65.180057,7.075947e+06,NaN,5.946000,6.354000,6.164000,2017,Bulgaria,BGR,NaN,0,Earth
25,Burkina Faso,17.506481,3.972831,10.0,6.911902,734.994430,2044.381874,61.430000,59.981000,60.768000,70.150892,1.919328e+07,NaN,9.130000,3.862000,6.216000,2017,Burkina Faso,BFA,DEVELOPING,0,Earth
26,Burundi,9.300000,NaN,NaN,7.517637,292.997631,773.571858,62.675000,59.092000,60.898000,421.613084,1.082702e+07,NaN,1.073000,1.934000,1.487000,2017,Burundi,BDI,DEVELOPING,0,Earth
27,Cabo Verde,91.415230,47.026308,10.0,5.360132,3292.645755,6643.204610,75.812000,69.089000,72.570000,133.373945,5.374970e+05,NaN,12.769000,11.828000,12.240000,2017,Cabo Verde,CPV,DEVELOPING,0,Earth
28,Cambodia,89.070000,16.722893,NaN,5.928473,1385.259980,3928.373688,71.318000,67.062000,69.289000,90.694618,1.600941e+07,NaN,0.813000,0.560000,0.683000,2017,Cambodia,KHM,DEVELOPING,0,Earth
29,Cameroon,61.342335,4.374703,6.0,3.492525,1425.107818,3554.525156,59.795000,57.235000,58.511000,51.968533,2.456604e+07,NaN,3.884000,2.996000,3.414000,2017,Cameroon,CMR,DEVELOPING,0,Earth
30,Canada,100.000000,228.429181,10.0,10.789648,45148.552706,48633.829775,84.100000,79.900000,81.948780,4.018616,3.654332e+07,NaN,5.849000,6.780000,6.340000,2017,Canada,CAN,DEVELOPED,0,Earth
31,Caribbean small states,97.767418,38.060084,6.5,6.417207,9767.970059,15612.302436,75.774674,71.339979,73.517491,18.068386,7.314986e+06,NaN,12.197514,7.484576,9.553455,2017,Caribbean small states,CSS,NaN,1,Earth
32,Central African Republic,29.834490,1.375746,10.0,6.665415,450.900245,912.802052,54.354000,50.152000,52.240000,7.377489,4.596028e+06,NaN,3.624000,3.837000,3.740000,2017,Central African Republic,CAF,DEVELOPING,0,Earth
33,Central Europe and the Baltics,100.000000,66.837126,10.0,6.578097,14244.864479,30018.236495,80.713471,73.369297,76.947465,92.971613,1.027387e+08,NaN,5.258638,5.322124,5.293338,2017,Central Europe and the Baltics,CEB,NaN,1,Earth
34,Chad,10.900000,1.531890,10.0,4.404453,665.948353,1587.031060,55.132000,52.315000,53.712000,11.925646,1.501677e+07,NaN,1.625000,2.033000,1.848000,2017,Chad,TCD,DEVELOPING,0,Earth
35,Chile,100.000000,51.598029,12.0,9.068205,14999.370089,23663.885292,82.333000,77.333000,79.909000,24.841484,1.847044e+07,NaN,7.455000,6.600000,6.958000,2017,Chile,CHL,NaN,0,Earth
36,China,100.000000,84.429515,9.0,5.151192,8879.438667,14344.421239,78.828000,74.315000,76.470000,147.674051,1.386395e+09,NaN,3.847000,4.905000,4.441000,2017,China,CHN,DEVELOPING,0,Earth
37,Colombia,98.500000,42.023478,12.0,7.678643,6376.706716,14313.916386,79.694000,74.124000,76.925000,44.082780,4.890984e+07,NaN,11.513000,6.866000,8.872000,2017,Colombia,COL,NaN,0,Earth
38,Comoros,79.419693,5.100094,6.0,4.648014,1323.811590,3032.254682,65.675000,62.210000,63.912000,437.341200,8.138920e+05,NaN,4.748000,4.106000,4.375000,2017,Comoros,COM,DEVELOPING,0,Earth
39,"Congo, Dem. Rep.",18.226164,NaN,6.0,4.157287,467.074237,1059.810775,61.539000,58.528000,60.026000,35.905147,8.139876e+07,NaN,3.426000,5.067000,4.273000,2017,"Congo, Dem. Rep.",COD,DEVELOPING,0,Earth
40,"Congo, Rep.",64.709854,9.504361,10.0,2.939538,2191.220438,4274.296414,65.316000,62.546000,63.954000,14.965452,5.110702e+06,NaN,10.361000,9.189000,9.763000,2017,"Congo, Rep.",COG,DEVELOPING,0,Earth
41,Costa Rica,99.600000,64.247154,13.0,7.328796,11814.626569,19112.408887,82.557000,77.354000,79.914000,96.943870,4.949954e+06,NaN,10.293000,6.819000,8.142000,2017,Costa Rica,CRI,NaN,0,Earth
42,Cote d'Ivoire,65.600000,7.103949,10.0,4.453035,2111.027076,4830.751701,58.320000,55.864000,57.017000,76.847387,2.443747e+07,NaN,3.858000,2.859000,3.273000,2017,Cote d'Ivoire,CIV,DEVELOPING,0,Earth
43,Croatia,100.000000,140.010144,8.0,6.778273,13451.624948,26673.766399,80.900000,74.900000,77.826829,73.704986,4.124531e+06,NaN,11.905000,10.611000,11.208000,2017,Croatia,HRV,NaN,0,Earth
44,Cyprus,100.000000,48.518850,10.0,6.738289,26338.694344,37766.901657,82.794000,78.547000,80.672000,127.670996,1.179680e+06,NaN,11.269000,10.865000,11.052000,2017,Cyprus,CYP,NaN,0,Earth
45,Czech Republic,100.000000,55.642045,9.0,7.231339,20636.199952,38973.552190,82.000000,76.100000,78.978049,137.198109,1.059444e+07,NaN,3.579000,2.337000,2.890000,2017,Czech Republic,CZE,DEVELOPED,0,Earth
46,Denmark,100.000000,49.166670,10.0,10.039634,57610.098180,55516.905270,83.100000,79.200000,81.102439,137.294118,5.764980e+06,NaN,5.936000,5.569000,5.743000,2017,Denmark,DNK,DEVELOPED,0,Earth
47,Djibouti,60.200000,12.102179,10.0,2.464763,2914.383856,4885.220563,68.023000,64.000000,65.893000,40.728947,9.440970e+05,NaN,10.507000,10.300000,10.382000,2017,Djibouti,DJI,DEVELOPING,0,Earth
48,Dominican Republic,100.000000,39.373701,15.0,5.830587,7609.338800,16735.332586,76.990000,70.609000,73.689000,217.618112,1.051313e+07,NaN,8.122000,4.320000,5.832000,2017,Dominican Republic,DOM,DEVELOPING,0,Earth
49,Early-demographic dividend,89.616826,27.013332,10.0,5.199678,3555.344906,8992.232983,72.158709,68.477227,70.254204,96.846232,3.206361e+09,NaN,6.554418,5.352228,5.709709,2017,Early-demographic dividend,EAR,NaN,1,Earth
50,East Asia & Pacific,97.857123,52.786700,9.0,6.574193,10467.443025,16334.026327,78.506192,73.405621,75.865954,94.852710,2.314098e+09,NaN,3.482658,4.218723,3.899911,2017,East Asia & Pacific,EAS,NaN,1,Earth
51,East Asia & Pacific (IDA & IBRD countries),98.268814,26.935369,9.0,4.911259,7249.101815,13123.151792,77.591859,72.659118,75.033359,129.338479,2.042688e+09,NaN,3.515438,4.311212,3.967301,2017,East Asia & Pacific (IDA & IBRD countries),TEA,NaN,1,Earth
52,East Asia & Pacific (excluding high income),97.626680,26.935369,9.0,4.911070,7173.567315,12986.322227,77.563102,72.607025,74.994952,129.961692,2.068143e+09,NaN,3.496936,4.295886,3.950132,2017,East Asia & Pacific (excluding high income),EAP,NaN,1,Earth
53,Ecuador,99.200000,33.189841,15.0,8.257429,6213.501276,11617.908758,79.442000,73.833000,76.584000,67.584800,1.678536e+07,NaN,4.929000,3.069000,3.836000,2017,Ecuador,ECU,DEVELOPING,0,Earth
54,"Egypt, Arab Rep.",100.000000,17.706670,12.0,5.633056,2444.290311,11014.486137,73.967000,69.453000,71.656000,96.883413,9.644259e+07,NaN,23.087000,8.252000,11.737000,2017,"Egypt, Arab Rep.",EGY,DEVELOPING,0,Earth
55,El Salvador,96.800000,37.239512,15.0,7.227560,3910.257193,8454.058198,77.417000,68.006000,72.872000,308.307046,6.388122e+06,NaN,4.006000,4.658000,4.385000,2017,El Salvador,SLV,DEVELOPING,0,Earth
56,Equatorial Guinea,66.775719,10.234212,6.0,3.010814,9667.912252,22551.083246,59.259000,57.059000,58.061000,44.991123,1.262001e+06,NaN,6.208000,6.643000,6.483000,2017,Equatorial Guinea,GNQ,DEVELOPING,0,Earth
57,Estonia,100.000000,67.773329,9.0,6.591838,20458.460729,33937.454679,82.600000,73.800000,78.092683,30.305590,1.317384e+06,NaN,5.299000,6.191000,5.760000,2017,Estonia,EST,DEVELOPED,0,Earth
58,Eswatini,73.500000,37.204044,7.0,6.910856,3914.613252,8408.454272,62.753000,54.329000,58.319000,65.392616,1.124753e+06,NaN,24.162001,21.014999,22.538000,2017,Eswatini,SWZ,DEVELOPING,0,Earth
59,Ethiopia,44.300000,NaN,8.0,3.503316,768.522308,2021.561046,67.784000,63.997000,65.872000,106.400024,1.064000e+08,NaN,2.811000,1.523000,2.120000,2017,Ethiopia,ETH,DEVELOPING,0,Earth
60,Euro area,100.000000,85.639518,10.0,10.158286,37140.669853,45788.687122,84.564658,79.433986,81.932215,127.351000,3.411636e+08,NaN,9.445836,8.730447,9.060117,2017,Euro area,EMU,NaN,1,Earth
61,Europe & Central Asia,99.992810,62.849062,10.0,9.262008,23629.106224,34110.496806,81.018596,74.745304,77.785425,33.330236,9.145855e+08,NaN,7.561297,7.434573,7.491877,2017,Europe & Central Asia,ECS,NaN,1,Earth
62,Europe & Central Asia (IDA & IBRD countries),99.985613,61.588435,10.0,5.342443,8552.952742,21968.882827,77.921981,70.057013,73.894596,19.882087,4.569764e+08,NaN,6.949660,7.265409,7.125451,2017,Europe & Central Asia (IDA & IBRD countries),TEC,NaN,1,Earth
63,Europe & Central Asia (excluding high income),99.983368,55.667175,10.5,5.122938,7879.818681,20874.078573,77.463883,69.546534,73.412709,17.653092,3.952897e+08,NaN,7.246555,7.557300,7.419553,2017,Europe & Central Asia (excluding high income),ECA,NaN,1,Earth
64,European Union,100.000000,67.773329,10.0,9.879009,33080.918644,42848.349333,83.746778,78.260329,80.930659,111.623133,4.461313e+08,NaN,8.442320,7.876072,8.135618,2017,European Union,EUU,NaN,1,Earth
65,Fiji,96.000000,52.650252,NaN,3.186896,6101.030839,13429.315918,69.043000,65.594000,67.252000,48.027313,8.774590e+05,NaN,5.553000,3.593000,4.237000,2017,Fiji,FJI,DEVELOPING,0,Earth
66,Finland,100.000000,32.472987,10.0,9.141566,46336.663253,47501.632372,84.500000,78.900000,81.631707,18.124491,5.508214e+06,NaN,8.389000,8.872000,8.640000,2017,Finland,FIN,DEVELOPED,0,Earth
67,Fragile and conflict affected situations,54.811972,4.863829,9.0,4.692825,2055.573604,4773.048905,62.958663,59.447214,61.204749,46.069263,7.635780e+08,NaN,7.654605,6.570142,7.010501,2017,Fragile and conflict affected situations,FCS,NaN,1,Earth
68,France,100.000000,102.273100,10.0,11.390502,38812.161034,44826.507474,85.700000,79.600000,82.575610,122.114008,6.686438e+07,NaN,9.336000,9.454000,9.397000,2017,France,FRA,DEVELOPED,0,Earth
69,Gabon,91.902283,NaN,10.0,2.780745,7230.396393,15006.764091,67.883000,63.879000,65.839000,8.013440,2.064823e+06,NaN,28.266001,14.433000,19.982000,2017,Gabon,GAB,DEVELOPING,0,Earth
70,"Gambia, The",56.200000,8.851275,9.0,3.340842,679.756914,2072.652450,62.840000,60.088000,61.440000,218.764229,2.213894e+06,NaN,12.406000,6.580000,9.136000,2017,"Gambia, The",GMB,DEVELOPING,0,Earth
71,Georgia,100.000000,76.034398,9.0,7.058044,4357.000936,13589.707392,77.816000,68.980000,73.414000,65.222786,3.728004e+06,NaN,12.691000,14.954000,13.939000,2017,Georgia,GEO,NaN,0,Earth
72,Germany,100.000000,118.932221,13.0,11.322296,44552.819372,53254.691865,83.400000,78.700000,80.992683,236.595495,8.265700e+07,NaN,3.315000,4.118000,3.746000,2017,Germany,DEU,DEVELOPED,0,Earth
73,Ghana,79.000000,11.288002,11.0,3.329778,2025.932424,4996.638706,64.503000,62.437000,63.463000,127.983963,2.912147e+07,NaN,4.385000,4.082000,4.223000,2017,Ghana,GHA,DEVELOPING,0,Earth
74,Greece,100.000000,61.558483,10.0,7.965225,18930.218628,28594.174479,83.900000,78.800000,81.287805,83.434282,1.075468e+07,NaN,26.115000,17.849001,21.488001,2017,Greece,GRC,DEVELOPED,0,Earth
75,Guatemala,93.300000,37.909262,16.0,5.813844,4451.450981,8317.364101,76.721000,70.830000,73.810000,150.125215,1.608742e+07,NaN,3.522000,1.939000,2.462000,2017,Guatemala,GTM,DEVELOPING,0,Earth
76,Guinea,35.400000,2.452492,6.0,4.274825,855.573640,2417.799187,61.153000,60.040000,60.706000,49.110935,1.206754e+07,NaN,3.326000,5.506000,4.318000,2017,Guinea,GIN,DEVELOPING,0,Earth
77,Guinea-Bissau,26.000000,4.850495,9.0,6.847081,738.549945,1925.237737,59.620000,55.597000,57.673000,65.012304,1.828146e+06,NaN,2.239000,2.740000,2.500000,2017,Guinea-Bissau,GNB,DEVELOPING,0,Earth
78,Guyana,90.863861,20.227597,6.0,5.659790,6124.929967,12005.358645,72.847000,66.605000,69.624000,3.938131,7.752210e+05,NaN,15.369000,9.919000,12.044000,2017,Guyana,GUY,DEVELOPING,0,Earth
79,Haiti,43.800000,2.263497,6.0,8.084683,1294.239746,2980.960856,65.454000,61.139000,63.290000,398.489332,1.098237e+07,NaN,16.773001,11.008000,13.735000,2017,Haiti,HTI,DEVELOPING,0,Earth
80,Heavily indebted poor countries (HIPC),42.184393,4.881259,8.5,5.175602,939.509104,2478.823927,64.485734,61.010078,62.748683,43.680036,7.591062e+08,NaN,4.825554,4.185483,4.474979,2017,Heavily indebted poor countries (HIPC),HPC,NaN,1,Earth
81,High income,99.995354,66.837126,10.0,12.483017,42013.889902,48379.567891,83.281367,78.061208,80.585465,34.627334,1.225031e+09,NaN,5.877960,5.351188,5.583461,2017,High income,HIC,NaN,1,Earth
82,Honduras,86.500000,23.717745,12.0,7.000699,2453.727896,5561.996312,77.201000,72.573000,74.898000,84.270382,9.429013e+06,NaN,8.016000,4.126000,5.528000,2017,Honduras,HND,DEVELOPING,0,Earth
83,"Hong Kong SAR, China",100.000000,50.431834,9.0,NaN,46165.856512,59849.248176,87.600000,81.900000,84.680488,7039.714286,7.391700e+06,NaN,2.774000,3.395000,3.090000,2017,"Hong Kong SAR, China",HKG,DEVELOPING,0,Earth
84,Hungary,100.000000,60.933893,13.0,6.792275,14605.854345,29832.097172,79.300000,72.500000,75.817073,108.118480,9.787966e+06,NaN,4.571000,3.809000,4.156000,2017,Hungary,HUN,DEVELOPING,0,Earth
85,IBRD only,96.868933,47.466702,10.0,5.555242,6094.414430,12551.471736,75.638930,70.936735,73.200079,66.739279,4.736170e+09,NaN,5.914822,5.773286,5.825845,2017,IBRD only,IBD,NaN,1,Earth
86,IDA & IBRD total,87.037854,27.206901,9.0,5.461896,4889.160082,10300.444286,73.090403,68.778474,70.864015,67.852623,6.333387e+09,NaN,5.775160,5.466676,5.583304,2017,IDA & IBRD total,IBT,NaN,1,Earth
87,IDA blend,64.607273,9.504361,9.5,3.650012,1718.482332,4786.718887,63.061180,60.755696,61.889041,122.869641,5.368629e+08,NaN,6.350652,4.811714,5.372280,2017,IDA blend,IDB,NaN,1,Earth
88,IDA only,54.378021,5.525135,9.0,4.527304,1118.026547,3122.811998,66.880137,63.094672,64.973034,58.889859,1.060354e+09,NaN,4.924290,4.076237,4.433095,2017,IDA only,IDX,NaN,1,Earth
89,IDA total,57.823681,7.103949,9.0,4.114783,1319.412191,3677.509220,65.610890,62.298013,63.936476,71.383728,1.597217e+09,NaN,5.319324,4.316782,4.721281,2017,IDA total,IDA,NaN,1,Earth
90,Iceland,100.000000,88.806068,10.0,8.343258,71310.939256,55562.426624,84.300000,81.100000,82.660976,3.425436,3.434000e+05,NaN,2.718000,2.763000,2.742000,2017,Iceland,ISL,DEVELOPED,0,Earth
91,India,92.600000,21.997341,8.0,3.535007,1981.651050,6185.993893,70.425000,68.000000,69.165000,450.243286,1.338659e+09,NaN,5.375000,5.430000,5.419000,2017,India,IND,DEVELOPING,0,Earth
92,Indonesia,98.140000,55.141566,9.0,2.868241,3837.651731,10935.841754,73.515000,69.156000,71.282000,146.086481,2.646459e+08,NaN,3.921000,4.352000,4.185000,2017,Indonesia,IDN,DEVELOPING,0,Earth
93,"Iran, Islamic Rep.",100.000000,77.519636,9.0,8.659664,5520.310471,14535.862226,77.436000,75.217000,76.271000,49.530901,8.067395e+07,NaN,19.872999,10.181000,12.100000,2017,"Iran, Islamic Rep.",IRN,DEVELOPING,0,Earth
94,Iraq,99.909851,2.657459,6.0,4.125017,5205.288255,10971.970012,72.318000,68.277000,70.294000,86.501632,3.755278e+07,NaN,31.020000,10.280000,13.020000,2017,Iraq,IRQ,DEVELOPING,0,Earth
95,Ireland,100.000000,89.576752,10.0,7.154849,69822.347085,78128.181479,84.000000,80.400000,82.156098,69.783539,4.807388e+06,NaN,6.293000,7.065000,6.712000,2017,Ireland,IRL,DEVELOPED,0,Earth
96,Israel,100.000000,121.384448,15.0,7.497668,40541.862094,38966.662697,84.600000,80.600000,82.551220,402.647874,8.713300e+06,NaN,4.320000,4.121000,4.215000,2017,Israel,ISR,DEVELOPED,0,Earth
97,Italy,100.000000,92.378017,12.0,8.677740,32406.720315,41784.624714,85.200000,80.800000,82.946341,205.809169,6.053671e+07,NaN,12.388000,10.340000,11.211000,2017,Italy,ITA,DEVELOPED,0,Earth
98,Jamaica,97.964561,33.567132,6.0,6.143779,5069.183838,9598.370957,75.878000,72.708000,74.267000,269.700185,2.920853e+06,NaN,15.392000,8.428000,11.634000,2017,Jamaica,JAM,DEVELOPING,0,Earth

In [ ]:
import pandas as pd
wdi = pd.read_csv('world_development_indicators.csv')
wdi.head()

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,Country Name,Country Code,country_category,is_region,planet
0,Afghanistan,97.700000,1.213235,9.0,11.777236,519.884773,2058.383832,65.656000,62.70100,64.130000,55.595993,36296400.0,NaN,14.090000,10.416000,11.184000,2017,Afghanistan,AFG,DEVELOPING,0,Earth
1,Albania,100.000000,31.714076,9.0,5.010597,4531.020806,13037.010016,80.148000,76.60100,78.333000,104.870693,2873457.0,NaN,12.563000,14.590000,13.750000,2017,Albania,ALB,DEVELOPING,0,Earth
2,Algeria,100.000000,9.130677,10.0,6.380329,4111.294110,11737.409353,77.735000,75.30700,76.499000,17.377715,41389198.0,NaN,21.114000,10.021000,11.996000,2017,Algeria,DZA,DEVELOPING,0,Earth
3,Angola,41.962894,19.079250,6.0,2.791503,4095.812942,7310.901738,63.252000,57.67700,60.379000,23.916538,29816748.0,NaN,7.467000,6.769000,7.119000,2017,Angola,AGO,DEVELOPING,0,Earth
4,Arab World,90.283638,27.360620,9.0,5.561266,6108.588220,14562.367966,73.493366,69.92125,71.622526,36.669804,411898967.0,NaN,20.361396,8.097088,10.641313,2017,Arab World,ARB,NaN,1,Earth

In [ ]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    434 non-null    object
 1   access_to_electricity_pct       434 non-null    float64
 2   atms_per_100000                 406 non-null    float64
 3   compulsory_education_years      412 non-null    float64
 4   health_expenditure_pct_of_gdp   427 non-null    float64
 5   gdp_per_capita_usd              434 non-null    float64
 6   gdp_per_capita_ppp              434 non-null    float64
 7   life_expectancy_female          434 non-null    float64
 8   life_expectancy_male            434 non-null    float64
 9   life_expectancy                 434 non-null    float64
 10  population_density              432 non-null    float64
 11  population                      434 non-null    float64
 12  alcohol_consumption_per_capita  215 non-null    float64
 13  unemployment_rate_female        434 non-null    float64
 14  unemployment_rate_male          434 non-null    float64
 15  unemployment_rate               434 non-null    float64
 16  year                            434 non-null    int64
 17  country_category                282 non-null    object
 18  is_region                       434 non-null    int64
dtypes: float64(15), int64(2), object(2)
memory usage: 64.5+ KB

In [ ]:
wdi['alcohol_consumption_per_capita']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
        ...
429    8.66000
430        NaN
431    6.18124
432    6.54000
433    4.67000
Name: alcohol_consumption_per_capita, Length: 434, dtype: float64

In [ ]:
# pd.read_csv()

#     na_values : scalar, str, list-like, or dict, optional
#     Additional strings to recognize as NA/NaN. If dict passed, specific
#     per-column NA values.  By default the following values are interpreted as
#     NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
#     '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a',
#     'nan', 'null'.

In [ ]:
wdi.describe()

,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,is_region
count,434.000000,406.000000,412.000000,427.000000,434.000000,434.000000,434.000000,434.000000,434.000000,432.000000,4.340000e+02,215.000000,434.000000,434.000000,434.000000,434.000000,434.000000
mean,84.215517,48.128568,9.701456,6.433350,13599.891623,19925.226075,74.569474,69.866522,72.176272,209.973753,3.690135e+08,6.016516,8.404762,6.465617,7.047682,2017.500000,0.211982
std,24.389620,43.078263,2.206372,2.622327,18647.562977,19970.698889,7.676443,7.144252,7.334379,747.286538,1.049035e+09,3.783835,6.863858,4.535745,5.026820,0.500577,0.409184
min,9.300000,1.213235,5.000000,2.138482,271.752044,773.571858,54.354000,49.837000,52.240000,2.004286,1.019980e+05,0.003000,0.369000,0.052000,0.110000,2017.000000,0.000000
25%,70.842500,14.305347,9.000000,4.493300,1971.836316,4989.813770,69.050750,65.297750,66.988750,35.045644,4.312760e+06,2.720000,3.893250,3.796250,3.946283,2017.000000,0.000000
50%,98.912941,39.411075,10.000000,6.006967,5783.711368,13108.453526,76.088500,70.813500,73.585501,69.610676,1.604842e+07,5.837431,5.836087,5.351708,5.606500,2017.500000,0.000000
75%,100.000000,65.059316,11.000000,7.960797,15561.550814,28646.342748,80.144500,74.659500,77.162500,133.921155,1.026882e+08,9.095000,10.286000,8.001815,9.051000,2018.000000,0.000000
max,100.000000,272.592801,16.000000,17.003614,116654.261067,116786.479974,87.700000,82.300000,84.934146,7952.998418,7.591945e+09,15.090000,42.769001,25.238001,27.070999,2018.000000,1.000000

In [ ]:
wdi.describe().T

,count,mean,std,min,25%,50%,75%,max
access_to_electricity_pct,434.0,8.421552e+01,2.438962e+01,9.300000,7.084250e+01,9.891294e+01,1.000000e+02,1.000000e+02
atms_per_100000,406.0,4.812857e+01,4.307826e+01,1.213235,1.430535e+01,3.941107e+01,6.505932e+01,2.725928e+02
compulsory_education_years,412.0,9.701456e+00,2.206372e+00,5.000000,9.000000e+00,1.000000e+01,1.100000e+01,1.600000e+01
health_expenditure_pct_of_gdp,427.0,6.433350e+00,2.622327e+00,2.138482,4.493300e+00,6.006967e+00,7.960797e+00,1.700361e+01
gdp_per_capita_usd,434.0,1.359989e+04,1.864756e+04,271.752044,1.971836e+03,5.783711e+03,1.556155e+04,1.166543e+05
gdp_per_capita_ppp,434.0,1.992523e+04,1.997070e+04,773.571858,4.989814e+03,1.310845e+04,2.864634e+04,1.167865e+05
life_expectancy_female,434.0,7.456947e+01,7.676443e+00,54.354000,6.905075e+01,7.608850e+01,8.014450e+01,8.770000e+01
life_expectancy_male,434.0,6.986652e+01,7.144252e+00,49.837000,6.529775e+01,7.081350e+01,7.465950e+01,8.230000e+01
life_expectancy,434.0,7.217627e+01,7.334379e+00,52.240000,6.698875e+01,7.358550e+01,7.716250e+01,8.493415e+01
population_density,432.0,2.099738e+02,7.472865e+02,2.004286,3.504564e+01,6.961068e+01,1.339212e+02,7.952998e+03
population,434.0,3.690135e+08,1.049035e+09,101998.000000,4.312760e+06,1.604842e+07,1.026882e+08,7.591945e+09
alcohol_consumption_per_capita,215.0,6.016516e+00,3.783835e+00,0.003000,2.720000e+00,5.837431e+00,9.095000e+00,1.509000e+01
unemployment_rate_female,434.0,8.404762e+00,6.863858e+00,0.369000,3.893250e+00,5.836087e+00,1.028600e+01,4.276900e+01
unemployment_rate_male,434.0,6.465617e+00,4.535745e+00,0.052000,3.796250e+00,5.351708e+00,8.001815e+00,2.523800e+01
unemployment_rate,434.0,7.047682e+00,5.026820e+00,0.110000,3.946283e+00,5.606500e+00,9.051000e+00,2.707100e+01
year,434.0,2.017500e+03,5.005770e-01,2017.000000,2.017000e+03,2.017500e+03,2.018000e+03,2.018000e+03
is_region,434.0,2.119816e-01,4.091835e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00

In [ ]:
# Check if there is a null value (no value)
wdi.isna()

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,country_category,is_region
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
430,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
431,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
432,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
433,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Check if there is no null value (has a value)
wdi.notna()

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,country_category,is_region
0,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
430,True,True,True,True,False,True,True,True,True,True,True,True,False,True,True,True,True,True,True
431,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True
432,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
433,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
# Get the dataframe with/without null values, then sum
wdi.isna().sum()

country_name                        0
access_to_electricity_pct           0
atms_per_100000                    28
compulsory_education_years         22
health_expenditure_pct_of_gdp       7
gdp_per_capita_usd                  0
gdp_per_capita_ppp                  0
life_expectancy_female              0
life_expectancy_male                0
life_expectancy                     0
population_density                  2
population                          0
alcohol_consumption_per_capita    219
unemployment_rate_female            0
unemployment_rate_male              0
unemployment_rate                   0
year                                0
country_category                  152
is_region                           0
dtype: int64

In [ ]:
# Count the number of occurrences of each value in the alcohol_consumption_per_capita column
wdi['alcohol_consumption_per_capita'].value_counts()

0.690000    3
0.019000    2
4.333362    2
9.230000    2
0.430000    2
           ..
8.930000    1
2.300000    1
8.940000    1
4.065725    1
2.710000    1
Name: alcohol_consumption_per_capita, Length: 204, dtype: int64

In [ ]:
# NaN: not a number
# Counts the number of times each value appears in the alcohol_consumption_per_capita column, including missing cells (NaN)

# wdi['alcohol_consumption_per_capita'] selects the average per capita alcohol consumption column (a Series)
# value_counts() counts how many times each different value appears, sorted from most to least
# dropna=False is the most important point. By default, value_counts() ignores NaN
# When dropna=False is set, NaN is counted as a normal value and appears as a separate row in the results
wdi['alcohol_consumption_per_capita'].value_counts(dropna=False)

NaN         219
0.690000      3
2.050000      2
0.430000      2
4.333362      2
           ...
8.930000      1
2.300000      1
8.940000      1
4.065725      1
2.710000      1
Name: alcohol_consumption_per_capita, Length: 205, dtype: int64

In [ ]:
wdi.isna().sum(axis=1)

0      1
1      1
2      1
3      1
4      2
      ..
429    0
430    2
431    1
432    0
433    0
Length: 434, dtype: int64

In [ ]:
# Count the number of empty rows, then sum
# Axis = 1 takes the row (axis = 0 takes the column)
num_missing_by_row = wdi.isna().sum(axis=1)

In [ ]:
# Show lines with empty values
num_missing_by_row > 0

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
30      True
31      True
32      True
33      True
34      True
35      True
36      True
37      True
38      True
39      True
40      True
41      True
42      True
43      True
44      True
45      True
46      True
47      True
48      True
49      True
50      True
51      True
52      True
53      True
54      True
55      True
56      True
57      True
58      True
59      True
60      True
61      True
62      True
63      True
64      True
65      True
66      True
67      True
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75      True
76      True
77      True
78      True
79      True
80      True
81      True
82      True
83      True
84      True
85      True
86      True
87      True
88      True
89      True
90      True
91      True
92      True
93      True
94      True
95      True
96      True
97      True
98      True
99      True
100     True
101     True
102     True
103     True
104     True
105     True
106     True
107     True
108     True
109     True
110     True
111     True
112     True
113     True
114     True
115     True
116     True
117     True
118     True
119     True
120     True
121     True
122     True
123     True
124     True
125     True
126     True
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135     True
136     True
137     True
138     True
139     True
140     True
141     True
142     True
143     True
144     True
145     True
146     True
147     True
148     True
149     True
150     True
151     True
152     True
153     True
154     True
155     True
156     True
157     True
158     True
159     True
160     True
161     True
162     True
163     True
164     True
165     True
166     True
167     True
168     True
169     True
170     True
171     True
172     True
173     True
174     True
175     True
176     True
177     True
178     True
179     True
180     True
181     True
182     True
183     True
184     True
185     True
186     True
187     True
188     True
189     True
190     True
191     True
192     True
193     True
194     True
195     True
196     True
197     True
198     True
199     True
200     True
201     True
202     True
203     True
204     True
205     True
206     True
207     True
208     True
209     True
210     True
211     True
212     True
213     True
214     True
215     True
216     True
217    False
218    False
219    False
220    False
221     True
222     True
223    False
224    False
225    False
226    False
227    False
228     True
229    False
230     True
231     True
232    False
233    False
234    False
235     True
236    False
237    False
238     True
239    False
240     True
241     True
242    False
243     True
244    False
245     True
246    False
247    False
248     True
249     True
250     True
251     True
252     True
253    False
254     True
255    False
256     True
257     True
258     True
259    False
260     True
261     True
262    False
263    False
264    False
265    False
266     True
267     True
268     True
269     True
270    False
271    False
272    False
273    False
274    False
275    False
276     True
277     True
278     True
279     True
280     True
281     True
282     True
283    False
284     True
285    False
286     True
287    False
288     True
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297     True
298     True
299    False
300     True
301    False
302     True
303     True
304     True
305     True
306     True
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318     True
319    False
320    False
321     True
322    False
323    False
324     True
325     True
326     True
327     True
328    False
329     True
330    False
331    False
332    False
333     True
334    False
335     True
336     True
337     True
338    False
339    False
340     True
341     True
342    False
343    False
344     True
345    False
346     True
347     True
348     True
349     True
350     True
351     True
352    False
353    False
354     True
355    False
356     True
357    False
358    False
359    False
360    False
361    False
362    False
363     True
364    False
365     True
366    False
367    False
368     True
369     True
370     True
371     True
372    False
373    False
374     True
375    False
376    False
377    False
378     True
379    False
380     True
381     True
382     True
383     True
384    False
385    False
386    False
387    False
388     True
389    False
390     True
391     True
392     True
393    False
394    False
395     True
396     True
397    False
398     True
399     True
400    False
401     True
402    False
403    False
404     True
405     True
406     True
407     True
408    False
409    False
410    False
411     True
412     True
413    False
414    False
415    False
416    False
417     True
418    False
419     True
420    False
421    False
422     True
423    False
424     True
425     True
426     True
427    False
428     True
429    False
430     True
431     True
432    False
433    False
434     True
435     True
436     True
437     True
438     True
439     True
440     True
441    False
442     True
443    False
444     True
445     True
dtype: bool

In [ ]:
# number of empty lines
(num_missing_by_row > 0).sum()

319

In [ ]:
wdi.shape

(434, 19)

In [ ]:
wdi[num_missing_by_row > 0]

,country_name,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,country_category,is_region
0,Afghanistan,97.700000,1.213235,9.0,11.777236,519.884773,2058.383832,65.656000,62.701000,64.130000,55.595993,3.629640e+07,NaN,14.090000,10.416000,11.184000,2017,DEVELOPING,0
1,Albania,100.000000,31.714076,9.0,5.010597,4531.020806,13037.010016,80.148000,76.601000,78.333000,104.870693,2.873457e+06,NaN,12.563000,14.590000,13.750000,2017,DEVELOPING,0
2,Algeria,100.000000,9.130677,10.0,6.380329,4111.294110,11737.409353,77.735000,75.307000,76.499000,17.377715,4.138920e+07,NaN,21.114000,10.021000,11.996000,2017,DEVELOPING,0
3,Angola,41.962894,19.079250,6.0,2.791503,4095.812942,7310.901738,63.252000,57.677000,60.379000,23.916538,2.981675e+07,NaN,7.467000,6.769000,7.119000,2017,DEVELOPING,0
4,Arab World,90.283638,27.360620,9.0,5.561266,6108.588220,14562.367966,73.493366,69.921250,71.622526,36.669804,4.118990e+08,NaN,20.361396,8.097088,10.641313,2017,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425,Upper middle income,99.423212,54.376093,10.0,5.739787,8906.243876,16701.291315,78.040738,72.790446,75.328985,49.316919,2.837704e+09,6.170874,5.809633,5.812897,5.811807,2018,NaN,1
426,Uruguay,100.000000,120.067132,14.0,9.202700,17277.970111,22116.786596,81.359000,73.958000,77.770000,19.708028,3.449299e+06,6.920000,10.089000,6.873000,8.336000,2018,NaN,0
428,Vanuatu,61.864769,48.050330,NaN,3.373726,3125.257989,3204.679541,71.990000,68.847000,70.323000,24.009844,2.926800e+05,2.250000,4.898000,3.958000,4.368000,2018,DEVELOPING,0
430,West Bank and Gaza,100.000000,24.735190,10.0,NaN,3562.330943,6472.121785,75.595000,72.263000,73.895000,758.984551,4.569087e+06,NaN,41.849998,22.393999,26.256001,2018,DEVELOPING,0
431,World,89.588551,40.949620,10.0,9.848779,11385.675227,17025.827360,74.871815,70.398743,72.563282,59.617978,7.591945e+09,6.181240,5.580954,5.271615,5.392213,2018,NaN,1